### ISSUE TITLE
float64 queries should throw an error

### ISSUE THREAD

**Issue by kylemcdonald** [teemupitkanen/mrpt#10]
It looks like float64 queries are not supported. But the failure is silent, and mrpt still returns results. This created a really complicated debugging problem for me when comparing two datasets and i forgot that the datatype of one was float64. Here's an example of the issue:

https://gist.github.com/kylemcdonald/b9c6eb400ccf688457be6d57ade78c17

**Comment by ejaasaari** [comment]
Thanks!
