### ISSUE TITLE
Unit Tests for Eigen version changes

### ISSUE THREAD

**Issue by jordanjuras** [teemupitkanen/mrpt#16]
Hi !

I am wondering if you have a suite of unit tests for this library? Specifically, I am working with a codebase that uses different version of Eigen, and I would like to ensure that all functions continue to work as expected - and also to ensure compatibility as Eigen continues to change.

**Comment by vioshyvo** [comment]
Hi, yes we have tests. They are found here: https://github.com/vioshyvo/RP-test

To use different version of Eigen in tests, you can tweak paths in the Makefile (https://github.com/vioshyvo/RP-test/blob/master/test/Makefile). It seems that the Makefile assumes Eigen is located at cpp/lib of the mrpt directory.

Please let us know if it works!

**Comment by jordanjuras** [comment]
Fantastic, thanks for responding so quickly. 
It does work.
