### ISSUE TITLE
Cannot load index from file

### ISSUE THREAD

**Issue by NoordGuy** [teemupitkanen/mrpt#17]
Hello!

As written in the docs it should be possible to load a saved index via the constructor:

`def __init__(self, data, shape=None, mmap=False)`
`param data: Input data either as a NxDim numpy ndarray or as a filepath to a binary file containing the data.`
`param shape: Shape of the data as a tuple (N, dim). Needs to be specified only if loading the data from a file.`

The following test script crashes (using python 3.7 and Windows 10) without further notice:

`import mrpt, numpy as np`
`data = np.random.rand(10000,512).astype(np.float32)`
`index = mrpt.MRPTIndex(data)`
`index.build_autotune_sample(0.9, 5)`
`index.save('testindex.sav')`
`index2 = mrpt.MRPTIndex('testindex.sav',(10000,512))`

Am I doing sth. wrong or is there an error within the c++ code?

**Comment by ejaasaari** [comment]
The save method saves the index but not the data matrix, so the proper way to load an index is

```
index2 = mrpt.MRPTIndex(data)
index2.load('testindex.sav')
```

**Comment by NoordGuy** [comment]
Thank you for your quick answer. I see where you are going. Saving two files (data and index) or generating the data again would solve the problem, but I would have to keep the data in memory until I save it. Isn’t that redundant as the data is also present in the mrpt structure?

Could something like this be possible, introducing a `MRPTIndex.data()` function?

`import mrpt, numpy as np`
`data = np.random.rand(10000,512).astype(np.float32)`
`index = mrpt.MRPTIndex(data)`
`index.build_autotune_sample(0.9, 5)`

...later on...

`with open(datafile, 'wb') as f:`
&nbsp;&nbsp;&nbsp;&nbsp;`f.write(index.data())`
`index.save('testindex.sav')`

...in another live...

`with open(datafile, 'rb') as f:`
&nbsp;&nbsp;&nbsp;&nbsp;`data2 = f.read()`
`index2 = mrpt.MRPTIndex(data2)`
`index2 = mrpt.MRPTIndex('testindex.sav',(10000,512))`

**Comment by ejaasaari** [comment]
The MRPT index actually doesn't copy the data matrix for precisely that reason. It operates on the same underlying storage as the original numpy matrix, so saving the data and the index separately should be the way to go.

**Comment by NoordGuy** [comment]
Thank you very much.
