### ISSUE TITLE
ImportError: No module named mrpt

### ISSUE THREAD

**Issue by zhenv5** [teemupitkanen/mrpt#2]
Hi, I followed the instruction of the instruction to get the module file. But when I tried to run the demo, I still got the import error: No module named mrpt. 

Could you help me figure it out?

Thanks very much.

**Comment by teemupitkanen** [comment]
Make sure you have both the module file (mrptlib.so) and the python file mrpt.py in the python path. Sounds to me like python cannot find the latter in your case. For simplicity you can try just moving mrptlib.so, mrpt.py and the file you're trying to run (the one that imports mrpt, e.g. demo.py) into the same directory.

**Comment by zhenv5** [comment]
I put them in the same directory.

But got:

ImportError: /Codes/mrpt/mrptlib.so: undefined symbol: _ZNSt13random_device7_M_initERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

**Comment by ryanrhymes** [comment]
have you checked e.g. PYTHONPATH or other relevant environment variables?
