### ISSUE TITLE
Python installation failed on windows

### ISSUE THREAD

**Issue by sonEliksir** [teemupitkanen/mrpt#7]
I'm on windows 10 and trying to install mrpt for python (3.5). 
`pip install git+https://github.com/teemupitkanen/mrpt/` returns

> c:\python35\include\pyconfig.h(68): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\cl.exe' failed with exit status 2

Tried to launch `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat` as it said [here](https://stackoverflow.com/questions/40018405/cython-cannot-open-include-file-io-h-no-such-file-or-directory).  It added the file `io.h` file in the folder `C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\include` that i added to the system path. But i still have the same error, when lauching `pip install ...`

I also tried to launch the `pip install ...` from the **Visual c++ 2015 x86 x64 Cross Build Tools Command Prompt** but now, i have another error

> cpp/mrptmodule.cpp(14): fatal error C1083: Cannot open include file: 'sys/mman.h': No such file or directory
>     error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

Don't know what to do. Any help

**Comment by kartikvega** [comment]
Same issue, were you able to resolve it?

**Comment by ejaasaari** [comment]
MRPT should now work on Windows with the latest commit. Sorry for the delay!
